
org.gradle.logging.level=INFO

# user settings
#MAVEN_REPO = https://jcr.zhulinkeji.com/artifactory/maven/

group = tech.krpc.ext
# same with the rpc
version = 1.0.0
rpcVersion = 1.0.0.rc1

# same with bt-grpc
#quarkusMiniSupport=3.8.4
quarkusMiniSupport=3.33.2
# keep with the graal-sdk
#graalSdkVersion=24.0.1
