plugins {
    id "io.quarkus.extension"// version "2.4.0.Final"
}
//apply plugin:  'io.quarkus.extensions'

quarkusExtension {
    deploymentModule = 'ext-mybatis-deployment'
}

//configurations {
//    providedCompile
//}
//
//sourceSets {
//    main { compileClasspath += configurations.providedCompile }
//}

dependencies {
//    implementation platform("io.quarkus:quarkus-bom:${quarkusMiniSupport}")

    implementation "io.quarkus:quarkus-arc:${quarkusMiniSupport}"
    implementation "io.quarkus:quarkus-agroal:${quarkusMiniSupport}"
    api project(':mybatis')


    // maven provided
//    compileOnly "org.graalvm.nativeimage:svm:$graalSdkVersion"
    //only contains the classes required to develop substitutions.
    compileOnly 'org.graalvm.sdk:nativeimage:24.0.1'

    annotationProcessor("io.quarkus:quarkus-extension-processor:${quarkusMiniSupport}")
}