dependencies {
//    implementation platform("io.quarkus:quarkus-bom:${quarkusMiniSupport}")
    implementation "io.quarkus:quarkus-arc-deployment:${quarkusMiniSupport}"
    implementation "io.quarkus:quarkus-agroal-deployment:${quarkusMiniSupport}"
    implementation project(':ext-mybatis')
    annotationProcessor("io.quarkus:quarkus-extension-processor:${quarkusMiniSupport}")
}